// <auto-generated />
using System;
using Linea.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Linea.Infrastructure.Migrations
{
    [DbContext(typeof(LineaDbContext))]
    [Migration("20260728133906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Linea.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Linea.Domain.Entities.Equipment.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetProductionRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("Linea.Domain.Entities.GeneratedReports.GeneratedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateFilter")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EquipmentIdFilter")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineNameFilter")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShiftFilter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("generated_reports", (string)null);
                });

            modelBuilder.Entity("Linea.Domain.Entities.Reports.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionReportId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("defects", (string)null);
                });

            modelBuilder.Entity("Linea.Domain.Entities.Reports.Downtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("downtimes", (string)null);
                });

            modelBuilder.Entity("Linea.Domain.Entities.Reports.ProductionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoodCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OeePercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScrapCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("Date", "Shift", "LineName", "EquipmentId")
                        .IsUnique();

                    b.ToTable("production_reports", (string)null);
                });

            modelBuilder.Entity("Linea.Domain.Entities.Reports.Defect", b =>
                {
                    b.HasOne("Linea.Domain.Entities.Reports.ProductionReport", "ProductionReport")
                        .WithMany("Defects")
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("Linea.Domain.Entities.Reports.Downtime", b =>
                {
                    b.HasOne("Linea.Domain.Entities.Reports.ProductionReport", "ProductionReport")
                        .WithMany("Downtimes")
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("Linea.Domain.Entities.Reports.ProductionReport", b =>
                {
                    b.HasOne("Linea.Domain.Entities.Equipment.Equipment", "Equipment")
                        .WithMany("ProductionReports")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Linea.Domain.Entities.Equipment.Equipment", b =>
                {
                    b.Navigation("ProductionReports");
                });

            modelBuilder.Entity("Linea.Domain.Entities.Reports.ProductionReport", b =>
                {
                    b.Navigation("Defects");

                    b.Navigation("Downtimes");
                });
#pragma warning restore 612, 618
        }
    }
}
